name: masp_mobile
description: Aplikasi Presensi & Website MA Sunan Prawoto (MASP Mobile)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^7.0.0

  cupertino_icons: ^1.0.6

  # WebView untuk Presensi & Website
  webview_flutter: ^4.7.0

  # Splash Screen Animasi
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0

  # Simpan tema & bahasa
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Generator Icon Aplikasi
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/icon.png
